dist: xenial
sudo: true
language: bash

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - DOCKER_REPO=andreasfaerber/jaymoulin-jdownloader
    - PLATFORMS="linux/amd64,linux/arm64,linux/arm/v7"

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

before_install:
  - docker container run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker container run -d -p 1234:1234 --rm --name buildkitd --privileged moby/buildkit:latest --addr://0.0.0.0:1234
  - sudo docker container cp buildkitd:/usr/bin/buildctl /usr/local/bin/
  - export BUILDKIT_HOST="0.0.0.0://1234"

install:
  - buildctl build --progress=plain --frontend=dockerfile.v0 --local context=. --local dockerfile=. --opt filename=Dockerfile --opt platform=$PLATFORMS --opt build-arg:VERSION=\"master\" --opt build-arg:GITSHA=\"$TRAVIS_COMMIT\" --output type=image,\"name=$DOCKER_REPO:git-master\",push=true

after_failure:
  - buildctl debug workers ls
  - docker container logs buildkitd

notifications:
  email: false
